---

- name: Create tmp Directory
  hosts: 127.0.0.1
  connection: local
  tasks:

    - name: Create tmp Directory
      file: path=../../tmp state=directory


- name: Retrieve ROUTERS Device Information
  gather_facts: no
  hosts: routers
  tasks:

    - name: Send Show Commands
      ios_command:
        provider: "{{ provider }}"
        commands:
          - show run | inc hostname
          - show inventory | inc Hw
      register: info

    - name: Store Hostname
      set_fact:
        hostname: "{{ info.stdout[0].split()[1] }}"

    - name: Store Serial Number
      set_fact:
        serial_numbers: "{{ info.stdout[1].split()[7] }}"

    - name: Write Output to File
      template:
        src: serial_numbers.csv.j2
        dest: ../../tmp/{{ inventory_hostname }}.csv


- name: Retrieve SWITCHES Device Information
  gather_facts: no
  hosts: switches
  tasks:

    - name: Send Show Commands
      ios_command:
        provider: "{{ provider }}"
        commands:
          - show run | inc hostname
          - show version | inc System serial number
      register: info

    - name: Store Hostname
      set_fact:
        hostname: "{{ info.stdout[0].split()[1] }}"

    - name: Store Serial Number
      set_fact:
        serial_numbers: "{{ info.stdout[1].split()[4::5] | join('\n,') }}"

    - name: Write Output to File
      template:
        src: serial_numbers.csv.j2
        dest: ../../tmp/{{ inventory_hostname }}.csv


- name: Prepare Serial Number Report
  hosts: 127.0.0.1
  connection: local
  tasks:

    - name: Copy Header File into tmp Directory
      command: cp ./files/utils/001-serial_numbers_header.txt ../../tmp

    - name: Assemble Individual Device Reports
      assemble:
        src: '../../tmp/'
        dest: '../../tmp/serial_numbers.csv'
      run_once: true

    - name: Move Report into Shared Reports Directory
      command: mv ../../tmp/serial_numbers.csv ./files/reports/serial_numbers.csv

    - name: Remove tmp Directory
      file: path=../../tmp state=absent

