---

- name: Get Device Information
  gather_facts: no
  hosts: net_devices
  tasks:

    - name: Send Show Commands
      ios_command:
        provider: "{{ provider }}"
        commands:
          - show inventory
          - sh run | inc hostname
          - sh ver | inc image
      register: info
    - debug: var=info.stdout_lines
