---

- name: Create tmp Directory
  hosts: 127.0.0.1
  connection: local
  tasks:

    - name: Create tmp Directory
      file: path=../../tmp state=directory


- name: Install New Config
  gather_facts: no
  hosts: routers

  tasks:

    - name: Generate Configuration Files
      template:
        src: changes-OFF.cfg.j2
        dest: ../tmp/{{ ansible_host }}.cfg

    - name: Move Config into Configs Directory
      command: mv ../../tmp/{{ ansible_host }}.cfg ./configs

    - name: Save Pre-Changes Config
      ntc_save_config:
        platform: "{{ platform }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        host: "{{ ansible_host }}"
        local_file: pre-backups/{{ ansible_host }}-PRE.txt

    - name: Apply changes & generate diff
      napalm_install_config:
        hostname: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        dev_os: "{{ dev_os }}"
        config_file: configs/{{ ansible_host }}.cfg
        commit_changes: True
        replace_config: True
        diff_file: diffs/{{ ansible_host  }}.diff.txt

    - name: Save Post-Changes Config
      ntc_save_config:
        platform: "{{ platform }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        host: "{{ ansible_host }}"
        local_file: post-backups/{{ ansible_host }}-POST.txt

    - name: Remove tmp Directory
      file: path=../../tmp state=absent

