---
- name: Diff Devices
  gather_facts: no
  hosts: routers
  tasks:
    - name: Gen .diff file (discard change)
      napalm_install_config:
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        hostname: "{{ ansible_host }}"
        replace_config: True
        dev_os: "{{ dev_os }}"
        config_file: ./candidates/{{ inventory_hostname }}.candidate.txt
        commit_changes: False
        diff_file: ./diffs/{{ inventory_hostname }}.diff.txt
      register: diff
    - debug: var=diff
