---
- name: Fetch running-configs
  gather_facts: no
  hosts: net_devices
  tasks:

    - ntc_save_config:
        platform: "{{ platform }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        host: "{{ ansible_host }}"
        local_file: running-configs/{{ inventory_hostname }}-running-config.cfg
