---
- name: Copy Image
  gather_facts: no
  hosts: routers
  tasks:
    - ios_config:
        provider: "{{ cli }}"
        lines: ['file prompt quiet']
      register: fpq
    - debug: var=fpq
    - ios_command:
        provider: "{{ cli }}"
        commands:
          - copy tftp://192.168.0.5/c2900-universalk9-mz.SPA.154-3.M3.bin flash0:/
      register: copy
    - debug: var=copy.stdout_lines
    - ios_config:
        provider: "{{ cli }}"
        lines: ['boot system flash0:c2900-universalk9-mz.SPA.154-3.M3.bin']
      register: bsf
    - debug: var=bsf
    - ios_command:
        provider: "{{ cli }}"
        commands:
          - wr mem
      register: write_mem
    - debug: var=write_mem
    - ios_command:
        provider: "{{ cli }}"
        commands:
          - reload
      register: reload
    - debug: var=reload

