---
- name: upgrade image via scp
  gather_facts: no
  hosts: routers
  tasks:

    - ntc_save_config:
        platform: "{{ platform }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        host: "{{ ansible_host }}"
        local_file: pre-backups/{{ inventory_hostname }}-pre.txt
      register: wr
    - debug: var=wr

    - ntc_file_copy:
        local_file: /home/vagrant/shared/images/{{ image_two }}
        platform: "{{ platform }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        host: "{{ ansible_host }}"
        file_system: "flash0:"
      register: scp
    - debug: var=scp

    - ntc_install_os:
        platform: "{{ platform }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        host: "{{ ansible_host }}"
        system_image_file: "{{ image_two }}"
      register: install
    - debug: var=install

    - ntc_save_config:
        platform: "{{ platform }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        host: "{{ ansible_host }}"
        local_file: post-backups/{{ inventory_hostname }}-POST.txt
      register: wr
    - debug: var=wr

    - ntc_reboot:
        platform: "{{ platform }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        host: "{{ ansible_host }}"
        confirm: true
        timer: 1
      register: reboot
    - debug: var=reboot
