---

- name: upgrade image via scp
  gather_facts: no
  hosts: routers
  tasks:

    - ntc_save_config:
        platform: "{{ platform }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        host: "{{ ansible_host }}"
        local_file: pre-backups/{{ inventory_hostname }}-pre.txt

    - ntc_file_copy:
        local_file: ./images/{{ image_two }}
        platform: "{{ platform }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        host: "{{ ansible_host }}"
        file_system: "flash0:"

    - ntc_install_os:
        platform: "{{ platform }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        host: "{{ ansible_host }}"
        system_image_file: "{{ image_two }}"

    - ntc_save_config:
        platform: "{{ platform }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        host: "{{ ansible_host }}"
        local_file: post-backups/{{ inventory_hostname }}-POST.txt

    - ntc_reboot:
        platform: "{{ platform }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        host: "{{ ansible_host }}"
        confirm: true
        timer: 1

