---

- name: Create tmp Directory
  hosts: 127.0.0.1
  connection: local
  tasks:

    - name: Create tmp Directory
      file: path=../../tmp state=directory


- name: Show Run To File
  gather_facts: no
  hosts: net_devices
  tasks:

    - name: execute show run command
      ios_command:
        provider: "{{ provider }}"
        commands:
          - show run
      register: output

    - name: write output to file
      template:
        src: output.txt.j2
        dest: ../../tmp/{{ ansible_host }}.txt


- name: Move Show Files
  hosts: 127.0.0.1
  connection: local
  tasks:

    - name: Ensure Show Files Directory is empty
      file: path=./files/show_files state=absent
      file: path=./files/show_files state=directory

    - name: Move Report into Shared Reports Directory
      command: mv ../../tmp/ ./files/show_files

    - name: Remove tmp Directory
      file: path=../../tmp state=absent

