---
- name: test
  hosts: 127.0.0.1
  connection: local
  tasks:

    - name: Move Report into Shared Reports Directory
      command: mv {{ local_home }}/tmp/serial_numbers.csv ./files/reports/serial_numbers.csv

