---

- name: upgrade image via scp
  gather_facts: no
  hosts: routers
  vars:
      image: "{{ image_two }}"
  tasks:

    - ntc_save_config:
        platform: "{{ platform }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        host: "{{ ansible_host }}"
        local_file: files/backups/pre-changes/{{ inventory_hostname }}-pre.txt

    - ntc_file_copy:
        local_file: files/cisco_images/{{ image }}
        platform: "{{ platform }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        host: "{{ ansible_host }}"
        file_system: "flash0:"

    - ntc_install_os:
        platform: "{{ platform }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        host: "{{ ansible_host }}"
        system_image_file: "{{ image }}"

    - ntc_save_config:
        platform: "{{ platform }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        host: "{{ ansible_host }}"
        local_file: files/backups/post-changes/{{ inventory_hostname }}-POST.txt

    - ntc_reboot:
        platform: "{{ platform }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        host: "{{ ansible_host }}"
        confirm: true
        timer: 1

